name: CI
on: 
push: 
branches:
- "**"

jobs:
build:
runs-on:ubuntu-latest
steps:
- user: actions/checkout@v3
- user: pnpm/action-setup@v2
with: 
version: 7
- user: actions/checkout@v3
with:
node-version: 16.x
chache: "pnpm"

- run: pnpm install --frozen-lockfile
- run: pnpm run lint && pnm run build

