name: Publish
on: 
push: 
branches:
-"main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
build:
runs-on:ubuntu-latest
steps:
-user: actions/checkout@v3
-user: pnpm/action-setup@v2
with: 
version: 7
-user: actions/checkout@v3
with:
node-version: 16.x
chache: "pnpm"

-run: pnpm install --frozen-lockfile
-name: Create Realase Pull Request or Publish
id: changesets
uses: changesets/action@v1

